### ISSUE TITLE
469-Week 预习周心德

### ISSUE THREAD

**Issue by smallverse** [algorithm004-04/algorithm004-04#17]
系统的对数据结构和算法进行了了解，赞！

自己绘制的脑图：https://www.yuque.com/docs/share/36d67c5f-310f-48f3-b270-913af4fc6dae

**Comment by wanchaosoft** [comment]
我们还可以在后续的学习过程中，对照着脑图，一步一步完善，点亮技能树。
`总-分-总`，还是很有成就感的。😁

**Comment by TuringZhai** [comment]
是的，我这边目前除了整体对数据结构和算法树有个整体印象后，后续要按照自己掌握的进度逐步画出，争取牢固掌握。


下面是我在学习过程中将要逐步完善的树：
https://www.yuque.com/turingzhai/fdl49y/sv5n1e





------------------ 原始邮件 ------------------
发件人: "wanchaosoft"<notifications@github.com>;
发送时间: 2019年10月13日(星期天) 晚上7:19
收件人: "algorithm004-04/algorithm004-04"<algorithm004-04@noreply.github.com>;
抄送: "翟俊峰"<zhaijunfeng-2012@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [algorithm004-04/algorithm004-04] 469-Week 预习周心德 (#17)




我们还可以在后续的学习过程中，对照着脑图，一步一步完善，点亮技能树。
 总-分-总，还是很有成就感的。😁
